griffin:
  image: bhlx3lyx7/svc_msr:0.1.6
  hostname: griffin
  links:
    - es
    - zk
    - kafka
  environment:
    ES_HOSTNAME: es
    ZK_HOSTNAME: zk
    KAFKA_HOSTNAME: kafka
  ports:
    - 32122:2122
    - 38088:8088
    - 33306:3306
    - 38042:8042
    - 39083:9083
    - 38998:8998
    - 38080:8080
  tty: true
  container_name: griffin

es:
  image: bhlx3lyx7/elasticsearch
  hostname: es
  ports:
    - 39200:9200
  container_name: es

zk:
  image: zookeeper:3.5
  hostname: zk
  ports:
    - 32181:2181
  container_name: zk
  restart: always

kafka:
  image: bhlx3lyx7/kafka
  hostname: kafka
  ports:
    - 39092:9092
  container_name: kafka
  tty: true
